### ISSUE TITLE
Error on getting uid

### ISSUE THREAD

**Issue by shirshak55** [borntyping/rust-psutil#63]
Please provide any of the following information if relevant:

- rust-psutil version:
- target platform info

	- (if linux) distro: Linux ubuntu 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- any relevant hardware info:

the code look like this
```
                let process_id = &process.uids().expect("Unable to get Id").real;
```

and it panics

```
thread 'main' panicked at 'Unable to get Id: IoError { pid: 1, source: Custom { kind: InvalidData, error: "Expected 55 lines, got 54" } }', src/libcore/result.rs:1165:5
```

It says excepected 55 lines and got 54 .

**Comment by cjbassi** [comment]
Just pushed a fix, can you test it out?

**Comment by shirshak55** [comment]
alright will let you know :)

**Comment by shirshak55** [comment]
@cjbassi hmm now i think i am getting another error.
```
thread 'main' panicked at 'Unable to get Id: IoError { pid: 3, source: Custom { kind: InvalidData, error: "Expected 2 fields, got 3" } }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Source code:

https://github.com/kuhpc/kill-em-all/blob/master/src/main.rs#L28

**Comment by cjbassi** [comment]
That's weird, it seems that one of the lines in the status file for a process contains two colons instead of just one. Can you figure out which process is causing the issue and then inspect its status file in procfs?

**Comment by shirshak55** [comment]
@cjbassi where is that procfs file?

**Comment by cjbassi** [comment]
`/proc/[pid]/status`

**Comment by cjbassi** [comment]
You can just copy the contents here

**Comment by shirshak55** [comment]
for 1 it is 
```
➜  ~ cat /proc/1/status
Name:	systemd
Umask:	0000
State:	S (sleeping)
Tgid:	1
Ngid:	0
Pid:	1
PPid:	0
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	128
Groups:
NStgid:	1
NSpid:	1
NSpgid:	1
NSsid:	1
VmPeak:	   77840 kB
VmSize:	   77840 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	    8812 kB
VmRSS:	    8812 kB
RssAnon:	    2316 kB
RssFile:	    6496 kB
RssShmem:	       0 kB
VmData:	    1920 kB
VmStk:	     132 kB
VmExe:	    1336 kB
VmLib:	   10016 kB
VmPTE:	     192 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
CoreDumping:	0
Threads:	1
SigQ:	0/80186
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	7be3c0fe28014a03
SigIgn:	0000000000001000
SigCgt:	00000001800004ec
CapInh:	0000000000000000
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Speculation_Store_Bypass:	thread vulnerable
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	11373
nonvoluntary_ctxt_switches:	729
➜  ~
```

**Comment by shirshak55** [comment]
for 2
```
➜  ~ cat /proc/2/status
Name:	kthreadd
Umask:	0000
State:	S (sleeping)
Tgid:	2
Ngid:	0
Pid:	2
PPid:	0
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	64
Groups:
NStgid:	2
NSpid:	2
NSpgid:	0
NSsid:	0
Threads:	1
SigQ:	0/80186
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	ffffffffffffffff
SigCgt:	0000000000000000
CapInh:	0000000000000000
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Speculation_Store_Bypass:	thread vulnerable
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	746
nonvoluntary_ctxt_switches:	0
```

**Comment by cjbassi** [comment]
You should just rerun your program and figure out which process is causing the issue to just copy that process status file

**Comment by shirshak55** [comment]
always its 3.
```
➜  kill-em-all git:(master) cat /proc/3/status
Name:	kworker/0:0
Umask:	0000
State:	I (idle)
Tgid:	3
Ngid:	0
Pid:	3
PPid:	2
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	64
Groups:
NStgid:	3
NSpid:	3
NSpgid:	0
NSsid:	0
Threads:	1
SigQ:	0/80186
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	ffffffffffffffff
SigCgt:	0000000000000000
CapInh:	0000000000000000
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Speculation_Store_Bypass:	thread vulnerable
Cpus_allowed:	01
Cpus_allowed_list:	0
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	120892
nonvoluntary_ctxt_switches:	1
```

**Comment by cjbassi** [comment]
Oh nice :) thanks.

**Comment by shirshak55** [comment]
i think it should show like this line of this file caused error. Like nom parser?

**Comment by cjbassi** [comment]
Yeah I agree, it would be nice to add some context to the error messages. I need to go throughout the library and add context to each error.

**Comment by cjbassi** [comment]
All right, I just pushed a fix.

**Comment by shirshak55** [comment]
@cjbassi fixed. Sorry for bothering you :)

**Comment by cjbassi** [comment]
No probs, I appreciate you helping improve the library :)
